// Code generated by menu-creator. DO NOT EDIT.
// Source: Canterbury.pdf
// Generated: 2025-01-24 16:11:04
// Location: Canterbury Golf

package seeding

import (
	"github.com/grow-assistant/menu-creator/internal/models"
)

// CreateCanterburyGolf generates seed data for Canterbury Golf location
// This includes all menus, categories, items, and their options
func CreateCanterburyGolf() *models.Location {
	// Create location
	location := models.CreateLocation("Canterbury Golf", "2323 Canterbury Drive")

	
	// Create menu: Main Menu
	menu := models.CreateMenu("Main Menu", "Main Menu", location.ID)
	location.Menus = append(location.Menus, *menu)

	
	// Create category: Starters
	category := models.CreateCategory("Starters", "", menu.ID)
	menu.Categories = append(menu.Categories, *category)

	
	// Create item: Crispy Calamari
	item := models.CreateItem(
		"Crispy Calamari",
		"Sweet chili sauce, peanuts, cilantro, scallions, sesame seeds, lime",
		0,
		category.ID,
	)
	category.Items = append(category.Items, *item)

	
	
	
	// Create category: Salads
	category := models.CreateCategory("Salads", "", menu.ID)
	menu.Categories = append(menu.Categories, *category)

	
	// Create item: Caesar Salad
	item := models.CreateItem(
		"Caesar Salad",
		"Black pepper parmesan crouton",
		0,
		category.ID,
	)
	category.Items = append(category.Items, *item)

	
	
	// Create item: Mixed Greens Salad
	item := models.CreateItem(
		"Mixed Greens Salad",
		"Mixed greens, cucumber, tomato, salumi, sweet peppers, olives, pepperoncini, chickpeas, provolone cheese, italian vinaigrette",
		0,
		category.ID,
	)
	category.Items = append(category.Items, *item)

	
	
	
	// Create category: Mains
	category := models.CreateCategory("Mains", "", menu.ID)
	menu.Categories = append(menu.Categories, *category)

	
	// Create item: Grilled Chicken Breast
	item := models.CreateItem(
		"Grilled Chicken Breast",
		"Pesto aioli, provolone, multi-grain bun, roasted sweet bell peppers",
		0,
		category.ID,
	)
	category.Items = append(category.Items, *item)

	
	
	// Create item: Roasted Prime Rib
	item := models.CreateItem(
		"Roasted Prime Rib",
		"Mushroom, onions, swiss cheese, au jus",
		0,
		category.ID,
	)
	category.Items = append(category.Items, *item)

	
	
	// Create item: Steak Frites
	item := models.CreateItem(
		"Steak Frites",
		"6 oz or 12 oz strip steak, maitre de butter, house cut parmesan fries, bernaise aioli",
		0,
		category.ID,
	)
	category.Items = append(category.Items, *item)

	
	
	
	// Create category: Cocktails
	category := models.CreateCategory("Cocktails", "", menu.ID)
	menu.Categories = append(menu.Categories, *category)

	
	// Create item: Crown Peach
	item := models.CreateItem(
		"Crown Peach",
		"Homemade ginger ale, lime juice, basil",
		0,
		category.ID,
	)
	category.Items = append(category.Items, *item)

	
	
	
	// Create category: Beers
	category := models.CreateCategory("Beers", "", menu.ID)
	menu.Categories = append(menu.Categories, *category)

	
	// Create item: Bud Light
	item := models.CreateItem(
		"Bud Light",
		"",
		0,
		category.ID,
	)
	category.Items = append(category.Items, *item)

	
	
	// Create item: Miller Lite
	item := models.CreateItem(
		"Miller Lite",
		"",
		0,
		category.ID,
	)
	category.Items = append(category.Items, *item)

	
	
	
	

	return location
}
